/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ExamplesIndexLazyImport = createFileRoute('/examples/')()
const AboutIndexLazyImport = createFileRoute('/about/')()
const ExamplesReactQueryLazyImport = createFileRoute('/examples/react-query')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ExamplesIndexLazyRoute = ExamplesIndexLazyImport.update({
  path: '/examples/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/examples/index.lazy').then((d) => d.Route),
)

const AboutIndexLazyRoute = AboutIndexLazyImport.update({
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about/index.lazy').then((d) => d.Route))

const ExamplesReactQueryLazyRoute = ExamplesReactQueryLazyImport.update({
  path: '/examples/react-query',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/examples/react-query.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/examples/react-query': {
      id: '/examples/react-query'
      path: '/examples/react-query'
      fullPath: '/examples/react-query'
      preLoaderRoute: typeof ExamplesReactQueryLazyImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/examples/': {
      id: '/examples/'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ExamplesReactQueryLazyRoute,
  AboutIndexLazyRoute,
  ExamplesIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/examples/react-query",
        "/about/",
        "/examples/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx"
    },
    "/examples/react-query": {
      "filePath": "examples/react-query.lazy.tsx"
    },
    "/about/": {
      "filePath": "about/index.lazy.tsx"
    },
    "/examples/": {
      "filePath": "examples/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
