/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'

// Create Virtual Routes

const LayoutSemesterIndexLazyImport = createFileRoute('/_layout/semester/')()
const LayoutProgramIndexLazyImport = createFileRoute('/_layout/program/')()
const LayoutPersonalIndexLazyImport = createFileRoute('/_layout/personal/')()
const LayoutFacultyIndexLazyImport = createFileRoute('/_layout/faculty/')()
const LayoutDutyPlanerIndexLazyImport = createFileRoute(
  '/_layout/dutyPlaner/',
)()
const LayoutAboutIndexLazyImport = createFileRoute('/_layout/about/')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSemesterIndexLazyRoute = LayoutSemesterIndexLazyImport.update({
  path: '/semester/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/semester/index.lazy').then((d) => d.Route),
)

const LayoutProgramIndexLazyRoute = LayoutProgramIndexLazyImport.update({
  path: '/program/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/program/index.lazy').then((d) => d.Route),
)

const LayoutPersonalIndexLazyRoute = LayoutPersonalIndexLazyImport.update({
  path: '/personal/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/personal/index.lazy').then((d) => d.Route),
)

const LayoutFacultyIndexLazyRoute = LayoutFacultyIndexLazyImport.update({
  path: '/faculty/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/faculty/index.lazy').then((d) => d.Route),
)

const LayoutDutyPlanerIndexLazyRoute = LayoutDutyPlanerIndexLazyImport.update({
  path: '/dutyPlaner/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/dutyPlaner/index.lazy').then((d) => d.Route),
)

const LayoutAboutIndexLazyRoute = LayoutAboutIndexLazyImport.update({
  path: '/about/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/about/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/about/': {
      id: '/_layout/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutIndexLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dutyPlaner/': {
      id: '/_layout/dutyPlaner/'
      path: '/dutyPlaner'
      fullPath: '/dutyPlaner'
      preLoaderRoute: typeof LayoutDutyPlanerIndexLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/faculty/': {
      id: '/_layout/faculty/'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof LayoutFacultyIndexLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/personal/': {
      id: '/_layout/personal/'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof LayoutPersonalIndexLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/program/': {
      id: '/_layout/program/'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof LayoutProgramIndexLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/semester/': {
      id: '/_layout/semester/'
      path: '/semester'
      fullPath: '/semester'
      preLoaderRoute: typeof LayoutSemesterIndexLazyImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutIndexRoute,
    LayoutAboutIndexLazyRoute,
    LayoutDutyPlanerIndexLazyRoute,
    LayoutFacultyIndexLazyRoute,
    LayoutPersonalIndexLazyRoute,
    LayoutProgramIndexLazyRoute,
    LayoutSemesterIndexLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/about/",
        "/_layout/dutyPlaner/",
        "/_layout/faculty/",
        "/_layout/personal/",
        "/_layout/program/",
        "/_layout/semester/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/about/": {
      "filePath": "_layout/about/index.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/dutyPlaner/": {
      "filePath": "_layout/dutyPlaner/index.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/faculty/": {
      "filePath": "_layout/faculty/index.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/personal/": {
      "filePath": "_layout/personal/index.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/program/": {
      "filePath": "_layout/program/index.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/semester/": {
      "filePath": "_layout/semester/index.lazy.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
